<style>
    h1,h2,h3,h4,h5,h6{
        font-family: "poppins";
        text-align: center;
    }
    .h8{
        font-family: "poppins";
        text-align: center;


    }

    body{
        background-image: url("images/bohe.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }


</style>



<?php 
$page_title = "Dashboard Page";
include('authentication.php');
include('includes/header.php');
include('includes/navbar.php'); 
?>

<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php
                    if(isset($_SESSION['status']))
                    {
                        ?>
                            <div class="alert alert-success">
                                <h9><?= $_SESSION['status']; ?></h9>
                            </div>
                            <?php
                            unset($_SESSION['status']);
                        }
                    ?>

                <div class="card">
                    <div class="card-header">
                    <h2>Welcome to The Bohemian Cafe</h2>
           
                    </div>
                    <div class="card-body">
                        <p class = "h8">Hello! <?= $_SESSION['auth_user']['username']; ?> Check The Types of Coffee</h8>
                        <br>
                        <!-- <h8 class = "h8">Email Address: <?= $_SESSION['auth_user']['email']; ?></h8> -->
                        <hr>
                        <h2>Types Of Coffee</h2>
                        <img src="images/kape.png" class="rounded mx-auto d-block"  usemap="#image_map">
                       <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="kape.png" usemap="#image-map">

<map name="image_map">
    <area target="" alt="latte" title="latte" href="https://en.wikipedia.org/wiki/Latte" coords="51,345,359,643" shape="rect">
    <area target="" alt="espresso" title="espresso" href="https://en.wikipedia.org/wiki/Espresso" coords="616,631,384,371" shape="rect">
    <area target="" alt="cappuccino" title="cappuccino" href="https://en.wikipedia.org/wiki/Cappuccino" coords="644,361,940,656" shape="rect">
    <area target="" alt="filter coffee" title="filter coffee" href="https://en.wikipedia.org/wiki/Coffee_filter" coords="46,698,353,981" shape="rect">
    <area target="" alt="americano" title="americano" href="https://en.wikipedia.org/wiki/Caffè_Americano" coords="370,703,637,987" shape="rect">
    <area target="" alt="instant coffee" title="instant coffee" href="https://en.wikipedia.org/wiki/Instant_coffee" coords="652,691,972,974" shape="rect">
</map>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include('includes/footer.php'); ?>

<!-- Messenger Chat Plugin Code -->
<div id="fb-root"></div>

<!-- Your Chat Plugin code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>

<script>
  var chatbox = document.getElementById('fb-customer-chat');
  chatbox.setAttribute("page_id", "135798353938391");
  chatbox.setAttribute("attribution", "biz_inbox");
</script>

<!-- Your SDK code -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      xfbml            : true,
      version          : 'v16.0'
    });
  };

  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<style>

